import type { SceneConfig } from '../engine/types';

/**
 * BRYGGA — the harbour, and the first playable chapter.
 *
 * Authored against "Læreøya game specification and visual art bible v1.0",
 * section 4.2. Every anchor below is the specification's own number, not a
 * position chosen by eye, which is why this file reads as data rather than
 * composition: the painted plate and the coordinates were designed together.
 *
 * UNITS. The specification works in logical units (LU) on a 360 x 640 design
 * canvas, with world art authored at 2 px per LU (section 2.1). The delivered
 * plate is 941 x 1672 px, so it covers 470 x 836 LU — which contains the whole
 * authored play space (x reaches 420 at the closed path marker, y runs 165 to
 * 816) with a little margin. Nothing is rescaled; the art sets the world size.
 */

/** Pixels per logical unit in the delivered background art. */
const PX_PER_LU = 2;

/** The plate's own size, in LU. */
const W = 941 / PX_PER_LU;
const H = 1672 / PX_PER_LU;

/**
 * Named positions, in LU.
 *
 * These are section 4.2's anchors re-derived against the delivered plate, not
 * its literal numbers. The specification authored them before the harbour was
 * painted, and the painting put the jetty around x = 231 where the anchors
 * assume x = 350 — spawning Ellie at the authored point stands her in open
 * water. The names, their meanings and their relationships are the
 * specification's; only the coordinates moved, and they moved to match the art.
 *
 * Exported because the chapter script needs to send Ellie to them by name; a
 * number repeated in two files is a number that will disagree with itself.
 */
export const BRYGGA_ANCHORS = {
  // Ashore on the sand, clear of the jetty's crossbar, as the target opens.
  // The traced bands put the crossbar at y 528-540 and the sand above it at
  // 492-528, so 538 still stood her on the timber.
  ellieSpawn: { x: 236, y: 512 },
  kikiSpawn: { x: 270, y: 520 },
  millaGround: { x: 300, y: 512 },
  millaApproach: { x: 262, y: 522 },
  basket: { x: 285, y: 528 },
  closedPath: { x: 230, y: 470 },
  meadowExit: { x: 226, y: 165 },
} as const;

/**
 * Where a character may stand.
 *
 * Generated by `node scripts/trace-walkable.mjs`, which classifies the plate's
 * own paint rather than approximating its shapes by eye. Section 3.2 requires
 * that "art contrast and shape must identify interactivity", so a walkable area
 * that disagrees with the painting tells the child one thing in pictures and
 * another in play.
 *
 * Bottom to top: the jetty spine, its crossbar widening onto the shore, then
 * the path corridor meandering north and narrowing to 63 LU at the meadow —
 * which is section 4.2's 64 LU minimum, give or take a pixel of brushwork.
 *
 * Re-run the tracer whenever the plate is repainted. Do not hand-edit.
 */
const WALKABLE = [
  { x: 222, y: 0, width: 63, height: 12 },
  { x: 242, y: 12, width: 61, height: 12 },
  { x: 245, y: 24, width: 63, height: 60 },
  { x: 234, y: 84, width: 66, height: 12 },
  { x: 222, y: 96, width: 68, height: 12 },
  { x: 212, y: 108, width: 65, height: 12 },
  { x: 209, y: 120, width: 50, height: 12 },
  { x: 184, y: 132, width: 82, height: 48 },
  { x: 193, y: 180, width: 84, height: 12 },
  { x: 201, y: 192, width: 90, height: 12 },
  { x: 212, y: 204, width: 89, height: 12 },
  { x: 222, y: 216, width: 91, height: 12 },
  { x: 226, y: 228, width: 98, height: 108 },
  { x: 209, y: 336, width: 96, height: 24 },
  { x: 191, y: 360, width: 102, height: 24 },
  { x: 183, y: 384, width: 93, height: 12 },
  { x: 172, y: 396, width: 115, height: 36 },
  { x: 180, y: 432, width: 121, height: 24 },
  { x: 182, y: 456, width: 123, height: 36 },
  { x: 160, y: 492, width: 154, height: 36 },
  { x: 71, y: 528, width: 329, height: 48 },
  { x: 174, y: 576, width: 124, height: 260 },
];

export const bryggaScene: SceneConfig = {
  id: 'brygga',
  world: { width: W, height: H },
  // Dusty blue, so any pixel the plate does not cover reads as more water
  // rather than as a hole.
  background: 0x408cad,
  camera: {
    // Framed as the visual target frames it: Ellie low in the view, the shore
    // and the way north above her.
    start: { x: 236, y: 400 },
    minZoom: 1,
    maxZoom: 1,
    // Section 2.1's design canvas. 360 LU across, so a 9:16 screen shows
    // 360 x 640 and Ellie's authored 66 LU is a tenth of it on any device.
    designWidth: 360,
  },

  layers: [
    {
      id: 'ground',
      asset: 'assets/worlds/brygga/ground.webp',
      layer: 'mid',
      parallax: 1,
      position: { x: 0, y: 0 },
      size: { width: W, height: H },
      placeholderColor: 0xa9a65d,
      placeholderLabel: 'Brygga',
    },
    /**
     * The near layer.
     *
     * Two painted pieces drawn in front of everything, including Ellie, at a
     * little over world speed. They do one job: stop the harbour reading as a
     * single flat picture with characters standing on it.
     *
     * Both are placed clear of the walkable corridor above — they are scenery
     * the child cannot tap, and a leaf that swallows a tap on the path is a
     * bug wearing a mood's clothing. The branch hangs in from the left edge
     * over the birch; the clump sits on the shore below it. Neither is an
     * interactable, so neither gets a hit area or an accessibility button.
     */
    {
      id: 'fore-branch',
      asset: 'assets/worlds/brygga/fore/birch-branch.png',
      layer: 'fore',
      parallax: 1.12,
      position: { x: -6, y: 186 },
      size: { width: 200, height: 112 },
      // Hanging, so it turns about its middle rather than about a base.
      ambient: { kind: 'sway', degrees: 1.4, period: 5200, pivot: 'center' },
    },
    {
      id: 'fore-grass',
      asset: 'assets/worlds/brygga/fore/grass-stone.png',
      layer: 'fore',
      parallax: 1.16,
      position: { x: -10, y: 462 },
      size: { width: 140, height: 79 },
      ambient: { kind: 'sway', degrees: 2, period: 4100, pivot: 'bottom' },
    },
  ],

  /**
   * The harbour's objects.
   *
   * Everything here sits in the sorted layer, so Ellie passes in front of what
   * is nearer the camera than her feet and behind what is further — which is
   * most of what makes a flat painting read as a place. x/y is the object's
   * centre; its depth is the line it stands on, half a height below.
   *
   * Positions are placed against the painted plate and checked on screen, not
   * derived from the specification's anchors: those were authored for a
   * harbour that had not been painted when they were written.
   */
  interactables: [
    {
      id: 'boathouse',
      x: 364,
      y: 420,
      hit: { shape: 'rect', width: 110, height: 100 },
      asset: 'assets/worlds/brygga/props/boathouse.png',
      size: { width: 110, height: 100 },
      label: 'Naustet',
    },
    {
      id: 'birch',
      x: 108,
      y: 300,
      hit: { shape: 'rect', width: 119, height: 150 },
      asset: 'assets/worlds/brygga/props/birch.png',
      size: { width: 119, height: 150 },
    },
    {
      id: 'boat',
      x: 372,
      y: 600,
      hit: { shape: 'rect', width: 46, height: 40 },
      asset: 'assets/worlds/brygga/props/boat.png',
      size: { width: 46, height: 40 },
      label: 'Robåten',
    },
    {
      id: 'post',
      x: 300,
      y: 556,
      hit: { shape: 'rect', width: 19, height: 45 },
      asset: 'assets/worlds/brygga/props/post.png',
      size: { width: 19, height: 45 },
    },
    // Milla and her basket, on the sand to the left of the path, where the
    // visual target puts them.
    {
      id: 'milla',
      x: 166,
      y: 470,
      hit: { shape: 'circle', radius: 24 },
      asset: 'assets/characters/milla/front.png',
      size: { width: 30, height: 34 },
      label: 'Milla',
      attention: true,
    },
    {
      id: 'basket',
      x: 200,
      y: 486,
      hit: { shape: 'circle', radius: 20 },
      asset: 'assets/worlds/brygga/props/basket-empty.png',
      size: { width: 44, height: 28 },
      label: 'Kurven',
    },
    // The three shells the counting task is about, spread along the path so
    // none of them crowds another or the route forward.
    {
      id: 'shell-1',
      x: 205,
      y: 440,
      hit: { shape: 'circle', radius: 16 },
      asset: 'assets/worlds/brygga/props/shells.png',
      size: { width: 23, height: 14 },
      label: 'Et skjell',
    },
    {
      id: 'shell-2',
      x: 276,
      y: 390,
      hit: { shape: 'circle', radius: 16 },
      asset: 'assets/worlds/brygga/props/shells.png',
      size: { width: 23, height: 14 },
      label: 'Et skjell',
    },
    {
      id: 'shell-3',
      x: 232,
      y: 318,
      hit: { shape: 'circle', radius: 16 },
      asset: 'assets/worlds/brygga/props/shells.png',
      size: { width: 23, height: 14 },
      label: 'Et skjell',
    },
    // The twigs across the path north. Section 4.2: an authored quest
    // boundary, not a claim that Ellie could not step over a twig.
    {
      id: 'twigs',
      x: 232,
      y: 258,
      hit: { shape: 'rect', width: 35, height: 18 },
      asset: 'assets/worlds/brygga/props/twigs.png',
      size: { width: 35, height: 18 },
      label: 'Kvister på stien',
    },
    // Milla again, up by the twigs, for the one beat where she clears them.
    // A second placement rather than a moving character: she has three painted
    // poses and no walk cycle, so walking her would mean sliding a standing
    // gull across the sand.
    {
      id: 'milla-at-twigs',
      x: 268,
      y: 256,
      hit: { shape: 'circle', radius: 24 },
      asset: 'assets/characters/milla/clear.png',
      // 50 x 28 is the clear pose's own aspect — she is reaching down, so she
      // is wider and shorter here than the 30 x 34 standing pose.
      size: { width: 50, height: 28 },
      label: 'Milla',
      hidden: true,
    },
  ],

  actors: [
    {
      id: 'ellie',
      sprites: {
        front: 'assets/characters/ellie/front.png',
        back: 'assets/characters/ellie/back.png',
        side: 'assets/characters/ellie/side.png',
      },
      // Section 3.2: 66 LU standing height including the beanie ears.
      height: 66,
      x: BRYGGA_ANCHORS.ellieSpawn.x,
      y: BRYGGA_ANCHORS.ellieSpawn.y,
      // Section 2.2: 84 LU/second, identical on diagonals.
      speed: 84,
      tapRadius: 30,
      label: 'Ellie',
    },
    {
      id: 'kiki',
      sprites: {
        front: 'assets/characters/kiki/front.png',
        back: 'assets/characters/kiki/back.png',
        side: 'assets/characters/kiki/side.png',
        rest: 'assets/characters/kiki/pose-rest.png',
      },
      // Section 3.2: 24 LU standing ear height. She should not reach Ellie's
      // waist, which 24 against 66 satisfies.
      height: 24,
      x: BRYGGA_ANCHORS.kikiSpawn.x,
      y: BRYGGA_ANCHORS.kikiSpawn.y,
      // Section 2.5: 92 LU/second following, 118 catching up.
      speed: 92,
      tapRadius: 18,
      label: 'Kiki',
      follows: 'ellie',
    },
  ],

  walkable: WALKABLE,

  /**
   * Artwork the chapter swaps in once the shells are found. Loaded with
   * everything else so the basket fills on the frame Milla thanks the child,
   * not a moment later.
   */
  preload: [
    'assets/characters/milla/talk.png',
    'assets/worlds/brygga/props/basket-full.png',
  ],
};
