import type { SceneConfig } from '../engine/types';

/**
 * BRYGGA — the harbour, and the first playable chapter.
 *
 * Authored against "Læreøya game specification and visual art bible v1.0",
 * section 4.2. Every anchor below is the specification's own number, not a
 * position chosen by eye, which is why this file reads as data rather than
 * composition: the painted plate and the coordinates were designed together.
 *
 * UNITS. The specification works in logical units (LU) on a 360 x 640 design
 * canvas, with world art authored at 2 px per LU (section 2.1). The delivered
 * plate is 941 x 1672 px, so it covers 470 x 836 LU — which contains the whole
 * authored play space (x reaches 420 at the closed path marker, y runs 165 to
 * 816) with a little margin. Nothing is rescaled; the art sets the world size.
 */

/** Pixels per logical unit in the delivered background art. */
const PX_PER_LU = 2;

/** The plate's own size, in LU. */
const W = 941 / PX_PER_LU;
const H = 1672 / PX_PER_LU;

/**
 * Named positions, in LU.
 *
 * These are section 4.2's anchors re-derived against the delivered plate, not
 * its literal numbers. The specification authored them before the harbour was
 * painted, and the painting put the jetty around x = 231 where the anchors
 * assume x = 350 — spawning Ellie at the authored point stands her in open
 * water. The names, their meanings and their relationships are the
 * specification's; only the coordinates moved, and they moved to match the art.
 *
 * Exported because the chapter script needs to send Ellie to them by name; a
 * number repeated in two files is a number that will disagree with itself.
 */
export const BRYGGA_ANCHORS = {
  // Ashore on the sand, clear of the jetty's crossbar, as the target opens.
  // The traced bands put the crossbar at y 528-540 and the sand above it at
  // 492-528, so 538 still stood her on the timber.
  ellieSpawn: { x: 236, y: 512 },
  kikiSpawn: { x: 270, y: 520 },
  millaGround: { x: 300, y: 512 },
  millaApproach: { x: 262, y: 522 },
  basket: { x: 285, y: 528 },
  closedPath: { x: 230, y: 470 },
  meadowExit: { x: 226, y: 165 },
} as const;

/**
 * Where a character may stand.
 *
 * Generated by `node scripts/trace-walkable.mjs`, which classifies the plate's
 * own paint rather than approximating its shapes by eye. Section 3.2 requires
 * that "art contrast and shape must identify interactivity", so a walkable area
 * that disagrees with the painting tells the child one thing in pictures and
 * another in play.
 *
 * Bottom to top: the jetty spine, its crossbar widening onto the shore, then
 * the path corridor meandering north and narrowing to 63 LU at the meadow —
 * which is section 4.2's 64 LU minimum, give or take a pixel of brushwork.
 *
 * Re-run the tracer whenever the plate is repainted. Do not hand-edit.
 */
const WALKABLE = [
  { x: 222, y: 0, width: 63, height: 12 },
  { x: 242, y: 12, width: 61, height: 12 },
  { x: 245, y: 24, width: 63, height: 60 },
  { x: 234, y: 84, width: 66, height: 12 },
  { x: 222, y: 96, width: 68, height: 12 },
  { x: 212, y: 108, width: 65, height: 12 },
  { x: 209, y: 120, width: 50, height: 12 },
  { x: 184, y: 132, width: 82, height: 48 },
  { x: 193, y: 180, width: 84, height: 12 },
  { x: 201, y: 192, width: 90, height: 12 },
  { x: 212, y: 204, width: 89, height: 12 },
  { x: 222, y: 216, width: 91, height: 12 },
  { x: 226, y: 228, width: 98, height: 108 },
  { x: 209, y: 336, width: 96, height: 24 },
  { x: 191, y: 360, width: 102, height: 24 },
  { x: 183, y: 384, width: 93, height: 12 },
  { x: 172, y: 396, width: 115, height: 36 },
  { x: 180, y: 432, width: 121, height: 24 },
  { x: 182, y: 456, width: 123, height: 36 },
  { x: 160, y: 492, width: 154, height: 36 },
  { x: 71, y: 528, width: 329, height: 48 },
  { x: 174, y: 576, width: 124, height: 260 },
];

export const bryggaScene: SceneConfig = {
  id: 'brygga',
  world: { width: W, height: H },
  // Dusty blue, so any pixel the plate does not cover reads as more water
  // rather than as a hole.
  background: 0x408cad,
  camera: {
    // Framed as the visual target frames it: Ellie low in the view, the shore
    // and the way north above her.
    start: { x: 236, y: 400 },
    minZoom: 1,
    maxZoom: 1,
    // Section 2.1's design canvas. 360 LU across, so a 9:16 screen shows
    // 360 x 640 and Ellie's authored 66 LU is a tenth of it on any device.
    designWidth: 360,
  },

  layers: [
    {
      id: 'ground',
      asset: 'assets/worlds/brygga/ground.webp',
      layer: 'mid',
      parallax: 1,
      position: { x: 0, y: 0 },
      size: { width: W, height: H },
      placeholderColor: 0xa9a65d,
      placeholderLabel: 'Brygga',
    },
  ],

  interactables: [],

  actors: [
    {
      id: 'ellie',
      sprites: {
        front: 'assets/characters/ellie/front.png',
        back: 'assets/characters/ellie/back.png',
        side: 'assets/characters/ellie/side.png',
      },
      // Section 3.2: 66 LU standing height including the beanie ears.
      height: 66,
      x: BRYGGA_ANCHORS.ellieSpawn.x,
      y: BRYGGA_ANCHORS.ellieSpawn.y,
      // Section 2.2: 84 LU/second, identical on diagonals.
      speed: 84,
      tapRadius: 30,
      label: 'Ellie',
    },
    {
      id: 'kiki',
      sprites: {
        front: 'assets/characters/kiki/front.png',
        back: 'assets/characters/kiki/back.png',
        side: 'assets/characters/kiki/side.png',
        rest: 'assets/characters/kiki/pose-rest.png',
      },
      // Section 3.2: 24 LU standing ear height. She should not reach Ellie's
      // waist, which 24 against 66 satisfies.
      height: 24,
      x: BRYGGA_ANCHORS.kikiSpawn.x,
      y: BRYGGA_ANCHORS.kikiSpawn.y,
      // Section 2.5: 92 LU/second following, 118 catching up.
      speed: 92,
      tapRadius: 18,
      label: 'Kiki',
      follows: 'ellie',
    },
  ],

  walkable: WALKABLE,
};
