/**
 * Writes ASSETS.md from the scene configs.
 *
 * The spec an illustrator works from has to be generated, not maintained by
 * hand — a hand-written one drifts from the code and then somebody paints to
 * numbers that stopped being true a month ago.
 *
 *   node scripts/assets.mjs
 */
import { build } from 'esbuild';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const tmp = join(root, 'node_modules', '.asset-build');
mkdirSync(tmp, { recursive: true });

const outfile = join(tmp, 'manifest.mjs');
await build({
  entryPoints: [join(root, 'src', 'world', 'assetManifest.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  packages: 'external',
  // The manifest only reads scene data, but SceneRenderer's dev-only fit check
  // touches import.meta.env; stub it so bundling stays clean.
  define: { 'import.meta.env.DEV': 'false' },
  logLevel: 'error',
});

const { ASSET_SLOTS, CHARACTER_SLOTS, CHARACTER_STATES } = await import(
  pathToFileURL(outfile).href
);

const byBand = new Map();
for (const slot of ASSET_SLOTS) {
  if (!byBand.has(slot.band)) byBand.set(slot.band, []);
  byBand.get(slot.band).push(slot);
}

const BAND_TITLES = {
  sky: 'Sky — furthest back, barely moves',
  far: 'Distant — mountains and treeline',
  mid: 'The island and everything on it',
  interactive: 'Places the child can tap',
  fore: 'Foreground framing — closest, moves most',
};

const lines = [];
lines.push('# OPPDAG — artwork for Læreøya');
lines.push('');
lines.push('**Generated by `node scripts/assets.mjs`. Do not edit by hand.**');
lines.push('');
lines.push('## Before you start');
lines.push('');
lines.push(
  '**The sizes below are not a demand.** They describe how much space the',
  'current composition gives each piece, using placeholder blocks that were',
  'invented to block the scene out. If your illustration has different',
  'proportions, send it as it is — the scene is plain data and gets refitted',
  'to the art. Stretching a painting to fit a number is how a hand-painted',
  'world starts looking subtly wrong.',
);
lines.push('');
lines.push('## Format');
lines.push('');
lines.push('- **WebP** preferred (PNG fine). Export at **2×** the listed size for retina.');
lines.push('- **Transparent** background everywhere except the three marked opaque.');
lines.push('- Drop files into `oppdag/public/` at the exact paths listed.');
lines.push(
  '- The dev server warns in the console if a file’s aspect ratio differs from',
  '  its slot by more than 2%, and tells you what to change.',
);
lines.push('');
lines.push('## The art bible');
lines.push('');
lines.push(
  'Hand-painted gouache/watercolour, colored-pencil linework, visible paper',
  'texture, warm Nordic palette, bright natural daylight. No airbrush, no dark',
  'vignettes, no glossy 3D. Characters: large-but-restrained eyes with a',
  'specular highlight, silhouette-first so they read at small sizes.',
);
lines.push('');

for (const [band, slots] of byBand) {
  lines.push(`## ${BAND_TITLES[band] ?? band}`);
  lines.push('');
  lines.push('| File | Size (1×) | Notes |');
  lines.push('| --- | --- | --- |');
  for (const slot of slots) {
    const notes = [];
    if (slot.opaque) notes.push('**opaque** — fills its box');
    else notes.push('transparent');
    if (slot.motion) notes.push(`animated: ${slot.motion}`);
    lines.push(`| \`${slot.path}\` | ${slot.width}×${slot.height} | ${notes.join('; ')} |`);
  }
  lines.push('');
}

lines.push('## Characters');
lines.push('');
lines.push(
  'Lumi is the guide who ships with the world; Kiki is the child’s own',
  'companion. Each needs one image per state. Companion staging rule: Kiki sits',
  'slightly behind and below the child’s eyeline, looking **up** — attentive,',
  'not posed.',
);
lines.push('');
lines.push('| File | Size (1×) | Role |');
lines.push('| --- | --- | --- |');
for (const character of CHARACTER_SLOTS) {
  for (const state of CHARACTER_STATES) {
    lines.push(
      `| \`assets/characters/${character.id}/${state}.webp\` | ` +
        `${character.width}×${character.height} | ${character.role} |`,
    );
  }
}
lines.push('');
lines.push(
  `_${ASSET_SLOTS.length} scene slots, ` +
    `${CHARACTER_SLOTS.length * CHARACTER_STATES.length} character states._`,
);
lines.push('');

writeFileSync(join(root, 'ASSETS.md'), lines.join('\n'), 'utf8');
rmSync(tmp, { recursive: true, force: true });
console.log(
  `ASSETS.md written — ${ASSET_SLOTS.length} scene slots, ` +
    `${CHARACTER_SLOTS.length * CHARACTER_STATES.length} character states`,
);
